/**
 * Riwi Learning Platform - Complementary Plan Model
 * Handles the persistence of AI-generated personalized learning paths.
 */

import { query } from '../config/database.js';

/**
 * Retrieves the current active plan for a coder.
 */
export async function getActivePlan(coderId) {
  const queryText = `
    SELECT * FROM complementary_plans 
    WHERE coder_id = $1 AND is_active = true
    ORDER BY generated_at DESC LIMIT 1
  `;
  const result = await query(queryText, [coderId]);
  return result.rows[0];
}

/**
 * Stores a new complementary plan generated by the AI service.
 */
export async function savePlan({ coderId, moduleId, planContent, priorityLevel = 'medium', softSkillsSnapshot = null, moodleStatusSnapshot = null }) {
  await query('UPDATE complementary_plans SET is_active = false WHERE coder_id = $1', [coderId]);

  const queryText = `
    INSERT INTO complementary_plans (coder_id, module_id, plan_content, priority_level, soft_skills_snapshot, moodle_status_snapshot, is_active, generated_at)
    VALUES ($1, $2, $3, $4, $5, $6, true, NOW())
    RETURNING *
  `;
  const result = await query(queryText, [coderId, moduleId, planContent, priorityLevel, softSkillsSnapshot, moodleStatusSnapshot]);
  return result.rows[0];
}
