/**
 * Riwi Learning Platform - Training Plan Model
 * Handles the persistence of AI-generated personalized learning paths.
 */

import { query } from '../config/database.js';

/**
 * Retrieves the current active plan for a coder.
 */
export async function getActivePlan(coderId) {
  const queryText = `
    SELECT * FROM complementary_plans 
    WHERE coder_id = $1 AND is_active = true
    ORDER BY generated_at DESC LIMIT 1
  `;
  const result = await query(queryText, [coderId]);
  return result.rows[0];
}

/**
 * Stores a new training plan generated by the AI service.
 */
export async function savePlan({ coderId, planContent, topic }) {
  await query(
    'UPDATE complementary_plans SET is_active = false WHERE coder_id = $1',
    [coderId]
  );

  const queryText = `
    INSERT INTO complementary_plans (coder_id, topic, plan_content, is_active, generated_at)
    VALUES ($1, $2, $3, true, NOW())
    RETURNING *
  `;
  const result = await query(queryText, [coderId, topic, planContent]);
  return result.rows[0];
}
